[package]
name = "copy_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
solana-sdk = "1.18.26"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4.3"
bs58 = "0.5.1"
solana-transaction-status = "1.18.26"
bincode = "1.3.3"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
futures = "0.3.31"
log = "0.4.22"

[build-dependencies]
tonic-build = "0.10"
prost-build = "0.12" 
