// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: arpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Transactions  map[string]*SubscribeRequestFilterTransactions `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PingId        *int32                                         `protobuf:"varint,2,opt,name=ping_id,json=pingId,proto3,oneof" json:"ping_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_arpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_arpc_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetTransactions() map[string]*SubscribeRequestFilterTransactions {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *SubscribeRequest) GetPingId() int32 {
	if x != nil && x.PingId != nil {
		return *x.PingId
	}
	return 0
}

type SubscribeRequestFilterTransactions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountInclude  []string               `protobuf:"bytes,2,rep,name=account_include,json=accountInclude,proto3" json:"account_include,omitempty"`
	AccountExclude  []string               `protobuf:"bytes,3,rep,name=account_exclude,json=accountExclude,proto3" json:"account_exclude,omitempty"`
	AccountRequired []string               `protobuf:"bytes,4,rep,name=account_required,json=accountRequired,proto3" json:"account_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeRequestFilterTransactions) Reset() {
	*x = SubscribeRequestFilterTransactions{}
	mi := &file_arpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequestFilterTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequestFilterTransactions) ProtoMessage() {}

func (x *SubscribeRequestFilterTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_arpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequestFilterTransactions.ProtoReflect.Descriptor instead.
func (*SubscribeRequestFilterTransactions) Descriptor() ([]byte, []int) {
	return file_arpc_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequestFilterTransactions) GetAccountInclude() []string {
	if x != nil {
		return x.AccountInclude
	}
	return nil
}

func (x *SubscribeRequestFilterTransactions) GetAccountExclude() []string {
	if x != nil {
		return x.AccountExclude
	}
	return nil
}

func (x *SubscribeRequestFilterTransactions) GetAccountRequired() []string {
	if x != nil {
		return x.AccountRequired
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp        `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Filters       []string                      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	Transaction   *SubscribeResponseTransaction `protobuf:"bytes,3,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_arpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_arpc_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SubscribeResponse) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SubscribeResponse) GetTransaction() *SubscribeResponseTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SubscribeResponseTransaction struct {
	state                       protoimpl.MessageState       `protogen:"open.v1"`
	Slot                        uint64                       `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	NumRequiredSignatures       uint32                       `protobuf:"varint,2,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32                       `protobuf:"varint,3,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32                       `protobuf:"varint,4,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	RecentBlockhash             []byte                       `protobuf:"bytes,5,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Signatures                  [][]byte                     `protobuf:"bytes,6,rep,name=signatures,proto3" json:"signatures,omitempty"`
	AccountKeys                 [][]byte                     `protobuf:"bytes,7,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	Instructions                []*CompiledInstruction       `protobuf:"bytes,8,rep,name=instructions,proto3" json:"instructions,omitempty"`
	AddressTableLookups         []*MessageAddressTableLookup `protobuf:"bytes,9,rep,name=address_table_lookups,json=addressTableLookups,proto3" json:"address_table_lookups,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SubscribeResponseTransaction) Reset() {
	*x = SubscribeResponseTransaction{}
	mi := &file_arpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponseTransaction) ProtoMessage() {}

func (x *SubscribeResponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_arpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponseTransaction.ProtoReflect.Descriptor instead.
func (*SubscribeResponseTransaction) Descriptor() ([]byte, []int) {
	return file_arpc_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponseTransaction) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SubscribeResponseTransaction) GetNumRequiredSignatures() uint32 {
	if x != nil {
		return x.NumRequiredSignatures
	}
	return 0
}

func (x *SubscribeResponseTransaction) GetNumReadonlySignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlySignedAccounts
	}
	return 0
}

func (x *SubscribeResponseTransaction) GetNumReadonlyUnsignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlyUnsignedAccounts
	}
	return 0
}

func (x *SubscribeResponseTransaction) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *SubscribeResponseTransaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *SubscribeResponseTransaction) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *SubscribeResponseTransaction) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *SubscribeResponseTransaction) GetAddressTableLookups() []*MessageAddressTableLookup {
	if x != nil {
		return x.AddressTableLookups
	}
	return nil
}

type MessageAddressTableLookup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKey      []byte                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WritableIndexes []byte                 `protobuf:"bytes,2,opt,name=writable_indexes,json=writableIndexes,proto3" json:"writable_indexes,omitempty"`
	ReadonlyIndexes []byte                 `protobuf:"bytes,3,opt,name=readonly_indexes,json=readonlyIndexes,proto3" json:"readonly_indexes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageAddressTableLookup) Reset() {
	*x = MessageAddressTableLookup{}
	mi := &file_arpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAddressTableLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAddressTableLookup) ProtoMessage() {}

func (x *MessageAddressTableLookup) ProtoReflect() protoreflect.Message {
	mi := &file_arpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAddressTableLookup.ProtoReflect.Descriptor instead.
func (*MessageAddressTableLookup) Descriptor() ([]byte, []int) {
	return file_arpc_proto_rawDescGZIP(), []int{4}
}

func (x *MessageAddressTableLookup) GetAccountKey() []byte {
	if x != nil {
		return x.AccountKey
	}
	return nil
}

func (x *MessageAddressTableLookup) GetWritableIndexes() []byte {
	if x != nil {
		return x.WritableIndexes
	}
	return nil
}

func (x *MessageAddressTableLookup) GetReadonlyIndexes() []byte {
	if x != nil {
		return x.ReadonlyIndexes
	}
	return nil
}

type CompiledInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Accounts       []byte                 `protobuf:"bytes,2,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompiledInstruction) Reset() {
	*x = CompiledInstruction{}
	mi := &file_arpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledInstruction) ProtoMessage() {}

func (x *CompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_arpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledInstruction.ProtoReflect.Descriptor instead.
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return file_arpc_proto_rawDescGZIP(), []int{5}
}

func (x *CompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *CompiledInstruction) GetAccounts() []byte {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *CompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_arpc_proto protoreflect.FileDescriptor

const file_arpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"arpc.proto\x12\x04arpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n" +
	"\x10SubscribeRequest\x12L\n" +
	"\ftransactions\x18\x01 \x03(\v2(.arpc.SubscribeRequest.TransactionsEntryR\ftransactions\x12\x1c\n" +
	"\aping_id\x18\x02 \x01(\x05H\x00R\x06pingId\x88\x01\x01\x1ai\n" +
	"\x11TransactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.arpc.SubscribeRequestFilterTransactionsR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_ping_id\"\xa1\x01\n" +
	"\"SubscribeRequestFilterTransactions\x12'\n" +
	"\x0faccount_include\x18\x02 \x03(\tR\x0eaccountInclude\x12'\n" +
	"\x0faccount_exclude\x18\x03 \x03(\tR\x0eaccountExclude\x12)\n" +
	"\x10account_required\x18\x04 \x03(\tR\x0faccountRequired\"\xc3\x01\n" +
	"\x11SubscribeResponse\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\afilters\x18\x02 \x03(\tR\afilters\x12I\n" +
	"\vtransaction\x18\x03 \x01(\v2\".arpc.SubscribeResponseTransactionH\x00R\vtransaction\x88\x01\x01B\x0e\n" +
	"\f_transaction\"\xf2\x03\n" +
	"\x1cSubscribeResponseTransaction\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x126\n" +
	"\x17num_required_signatures\x18\x02 \x01(\rR\x15numRequiredSignatures\x12?\n" +
	"\x1cnum_readonly_signed_accounts\x18\x03 \x01(\rR\x19numReadonlySignedAccounts\x12C\n" +
	"\x1enum_readonly_unsigned_accounts\x18\x04 \x01(\rR\x1bnumReadonlyUnsignedAccounts\x12)\n" +
	"\x10recent_blockhash\x18\x05 \x01(\fR\x0frecentBlockhash\x12\x1e\n" +
	"\n" +
	"signatures\x18\x06 \x03(\fR\n" +
	"signatures\x12!\n" +
	"\faccount_keys\x18\a \x03(\fR\vaccountKeys\x12=\n" +
	"\finstructions\x18\b \x03(\v2\x19.arpc.CompiledInstructionR\finstructions\x12S\n" +
	"\x15address_table_lookups\x18\t \x03(\v2\x1f.arpc.MessageAddressTableLookupR\x13addressTableLookups\"\x92\x01\n" +
	"\x19MessageAddressTableLookup\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\fR\n" +
	"accountKey\x12)\n" +
	"\x10writable_indexes\x18\x02 \x01(\fR\x0fwritableIndexes\x12)\n" +
	"\x10readonly_indexes\x18\x03 \x01(\fR\x0freadonlyIndexes\"o\n" +
	"\x13CompiledInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x01(\fR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data2Q\n" +
	"\vARPCService\x12B\n" +
	"\tSubscribe\x12\x16.arpc.SubscribeRequest\x1a\x17.arpc.SubscribeResponse\"\x00(\x010\x01BjZh/Users/ronaldwong/Library/Mobile Documents/com~apple~CloudDocs/Ronald/Documents/code/arbSniper/src/protob\x06proto3"

var (
	file_arpc_proto_rawDescOnce sync.Once
	file_arpc_proto_rawDescData []byte
)

func file_arpc_proto_rawDescGZIP() []byte {
	file_arpc_proto_rawDescOnce.Do(func() {
		file_arpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arpc_proto_rawDesc), len(file_arpc_proto_rawDesc)))
	})
	return file_arpc_proto_rawDescData
}

var file_arpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_arpc_proto_goTypes = []any{
	(*SubscribeRequest)(nil),                   // 0: arpc.SubscribeRequest
	(*SubscribeRequestFilterTransactions)(nil), // 1: arpc.SubscribeRequestFilterTransactions
	(*SubscribeResponse)(nil),                  // 2: arpc.SubscribeResponse
	(*SubscribeResponseTransaction)(nil),       // 3: arpc.SubscribeResponseTransaction
	(*MessageAddressTableLookup)(nil),          // 4: arpc.MessageAddressTableLookup
	(*CompiledInstruction)(nil),                // 5: arpc.CompiledInstruction
	nil,                                        // 6: arpc.SubscribeRequest.TransactionsEntry
	(*timestamppb.Timestamp)(nil),              // 7: google.protobuf.Timestamp
}
var file_arpc_proto_depIdxs = []int32{
	6, // 0: arpc.SubscribeRequest.transactions:type_name -> arpc.SubscribeRequest.TransactionsEntry
	7, // 1: arpc.SubscribeResponse.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: arpc.SubscribeResponse.transaction:type_name -> arpc.SubscribeResponseTransaction
	5, // 3: arpc.SubscribeResponseTransaction.instructions:type_name -> arpc.CompiledInstruction
	4, // 4: arpc.SubscribeResponseTransaction.address_table_lookups:type_name -> arpc.MessageAddressTableLookup
	1, // 5: arpc.SubscribeRequest.TransactionsEntry.value:type_name -> arpc.SubscribeRequestFilterTransactions
	0, // 6: arpc.ARPCService.Subscribe:input_type -> arpc.SubscribeRequest
	2, // 7: arpc.ARPCService.Subscribe:output_type -> arpc.SubscribeResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_arpc_proto_init() }
func file_arpc_proto_init() {
	if File_arpc_proto != nil {
		return
	}
	file_arpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_arpc_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arpc_proto_rawDesc), len(file_arpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arpc_proto_goTypes,
		DependencyIndexes: file_arpc_proto_depIdxs,
		MessageInfos:      file_arpc_proto_msgTypes,
	}.Build()
	File_arpc_proto = out.File
	file_arpc_proto_goTypes = nil
	file_arpc_proto_depIdxs = nil
}
