// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: arpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ARPCService_Subscribe_FullMethodName = "/arpc.ARPCService/Subscribe"
)

// ARPCServiceClient is the client API for ARPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ARPCServiceClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, SubscribeResponse], error)
}

type aRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewARPCServiceClient(cc grpc.ClientConnInterface) ARPCServiceClient {
	return &aRPCServiceClient{cc}
}

func (c *aRPCServiceClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ARPCService_ServiceDesc.Streams[0], ARPCService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ARPCService_SubscribeClient = grpc.BidiStreamingClient[SubscribeRequest, SubscribeResponse]

// ARPCServiceServer is the server API for ARPCService service.
// All implementations must embed UnimplementedARPCServiceServer
// for forward compatibility.
type ARPCServiceServer interface {
	Subscribe(grpc.BidiStreamingServer[SubscribeRequest, SubscribeResponse]) error
	mustEmbedUnimplementedARPCServiceServer()
}

// UnimplementedARPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedARPCServiceServer struct{}

func (UnimplementedARPCServiceServer) Subscribe(grpc.BidiStreamingServer[SubscribeRequest, SubscribeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedARPCServiceServer) mustEmbedUnimplementedARPCServiceServer() {}
func (UnimplementedARPCServiceServer) testEmbeddedByValue()                     {}

// UnsafeARPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ARPCServiceServer will
// result in compilation errors.
type UnsafeARPCServiceServer interface {
	mustEmbedUnimplementedARPCServiceServer()
}

func RegisterARPCServiceServer(s grpc.ServiceRegistrar, srv ARPCServiceServer) {
	// If the following call pancis, it indicates UnimplementedARPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ARPCService_ServiceDesc, srv)
}

func _ARPCService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ARPCServiceServer).Subscribe(&grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ARPCService_SubscribeServer = grpc.BidiStreamingServer[SubscribeRequest, SubscribeResponse]

// ARPCService_ServiceDesc is the grpc.ServiceDesc for ARPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ARPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arpc.ARPCService",
	HandlerType: (*ARPCServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ARPCService_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arpc.proto",
}
